#!/usr/bin/env escript 
%% -*- erlang -*-
%%! -pa ebin -name rpcclient

main([Node]) ->
	case rpc:call(list_to_atom(Node), erlbot, reload, []) of
		{badrpc, Reason} ->
			io:format(standard_error, "RPC call failed: ~p~n", [Reason]);
		Res ->
			io:format("~p~n", [Res])
	end;
main(_) ->
	io:format("Usage: ~ts <node>~n", [filename:basename(escript:script_name())]).
