#!/usr/bin/env escript 
%% -*- erlang -*-
%%! -pa ebin -name rpcclient

main([Node]) ->
	case rpc:call(list_to_atom(Node), irc_client, reload, []) of
		{badrpc, Reason} ->
			io:format(standard_error, "RPC call failed: ~p~n", [Reason]);
		ModuleList ->
			io:format("Modules reloaded: ~p~n", [ModuleList])
	end;
main(_) ->
	io:format("Usage: ~ts <node>~n", [filename:basename(escript:script_name())]).
